test_that("classical MDS reports rank and never takes negative square roots", {
  x <- rbind(c(0, 0), c(1, 0), c(0, 2), c(2, 3))
  X <- wrap.euclidean(x)
  out <- riem.mds(X, ndim = 3)
  expect_equal(as.matrix(dist(out$embed)), as.matrix(dist(x)), tolerance = 1e-10)
  expect_equal(out$effective_dimension, 2)
  expect_equal(out$embed[, 3], rep(0, 4))
  expect_lt(out$stress, 1e-10)
  constant <- riem.mds(wrap.euclidean(matrix(rep(1, 4), ncol = 1)), ndim = 2)
  expect_equal(constant$embed, matrix(0, 4, 2))
  expect_equal(constant$stress, 0)
  sphere <- wrap.sphere(rbind(c(1, 0), c(0, 1), c(-1, 0), c(0, -1)))
  curved <- riem.mds(sphere, ndim = 3)
  expect_true(length(curved$negative_eigenvalues) > 0)
  expect_true(all(is.finite(curved$embed)))
  expect_error(riem.mds(sphere, negative = "error"), "negative eigenvalue")
  expect_error(riem.mds(X, ndim = 4), "ndim")
})

test_that("kernel PCA uses sqrt eigenvalue scores in descending order", {
  x <- c(-1, 0, 1, 3)
  X <- wrap.euclidean(matrix(x, ncol = 1))
  sigma <- 1.2
  kernel <- exp(-outer(x, x, "-")^2 / (2 * sigma^2))
  H <- diag(4) - matrix(1 / 4, 4, 4)
  gram <- H %*% kernel %*% H
  out <- riem.kpca(X, ndim = 3, sigma = sigma)
  expect_equal(tcrossprod(out$embed), gram, tolerance = 1e-10)
  expect_equal(colSums(out$embed^2), out$vars[1:3], tolerance = 1e-10)
  expect_true(all(diff(out$vars) <= 0))
  expect_identical(out$kernel_status, "empirically_positive_semidefinite")
  expect_equal(dim(riem.kpca(X, ndim = 1)$embed), c(4L, 1L))
  expect_error(riem.kpca(X, sigma = 0), "positive")
  expect_error(riem.kpca(X, ndim = 4), "ndim")
  indefinite <- diag(c(1, 0.5, -0.2))
  expect_error(Riemann:::riem_legacy_eigen(indefinite, 2, "error"), "negative eigenvalue")
  truncated <- Riemann:::riem_legacy_eigen(indefinite, 2)
  expect_equal(truncated$negative_eigenvalues, -0.2)
})

test_that("Isomap uses mutual neighbors and exposes disconnected padding", {
  x <- c(0, 1, 3, 7)
  D <- abs(outer(x, x, "-"))
  graph <- Riemann:::riem_mutual_knn_graph(D, 1)
  expected <- matrix(FALSE, 4, 4)
  expected[1, 2] <- expected[2, 1] <- TRUE
  expect_identical(graph$adjacency, expected)
  expect_identical(graph$component, c(1L, 1L, 2L, 3L))
  X <- wrap.euclidean(matrix(x, ncol = 1))
  expect_error(riem.isomap(X, ndim = 1, nnbd = 1), "disconnected")
  expect_warning(out <- riem.isomap(X, ndim = 1, nnbd = 1, padding = TRUE), "artificial")
  expect_true(out$padded)
  expect_identical(out$adjacency, expected)
  complete <- riem.isomap(X, ndim = 1, nnbd = 3)
  expect_false(complete$padded)
  expect_equal(unname(as.matrix(dist(complete$embed))), D, tolerance = 1e-10)
  duplicated <- Riemann:::riem_mutual_knn_graph(abs(outer(c(0, 0, 1), c(0, 0, 1), "-")), 2)
  expect_true(duplicated$adjacency[1, 2])
  expect_equal(duplicated$distance[1, 2], 0)
})

reference_fanova_terms <- function(groups) {
  n <- sum(lengths(groups))
  proportions <- lengths(groups) / n
  all <- unlist(groups)
  squared <- lapply(groups, function(g) (g - mean(g))^2)
  v <- vapply(squared, mean, 0)
  s <- vapply(squared, function(z) mean(z^2) - mean(z)^2, 0)
  F <- mean((all - mean(all))^2) - sum(proportions * v)
  pairs <- combn(seq_along(groups), 2)
  U <- sum(apply(pairs, 2, function(ids) {
    prod(proportions[ids] / s[ids]) * diff(v[ids])^2
  }))
  c(variance = n * U / sum(proportions / s), mean = n * F^2 / sum(proportions^2 * s))
}

test_that("Frechet ANOVA matches equation14 with group proportions", {
  groups <- list(c(-1, 0, 2, 3), c(0, 1, 4, 8), c(-2, 1, 4, 7, 8))
  wrapped <- lapply(groups, function(x) wrap.euclidean(matrix(x, ncol = 1)))
  out <- do.call(riem.fanova, wrapped)
  reference <- reference_fanova_terms(groups)
  expect_equal(out$terms, reference, tolerance = 1e-10)
  expect_equal(unname(out$statistic), sum(reference), tolerance = 1e-10)
  expect_equal(out$p.value, pchisq(sum(reference), df = 2, lower.tail = FALSE), tolerance = 1e-10)
  expect_equal(out$group_proportions, lengths(groups) / sum(lengths(groups)))
  expect_identical(out$calibration, "asymptotic_chisquared")
  scaled <- lapply(groups, function(x) wrap.euclidean(matrix(x * 1e100, ncol = 1)))
  expect_equal(do.call(riem.fanova, scaled)$statistic, out$statistic, tolerance = 1e-10)
  expect_error(riem.fanova(wrapped[[1]]), "at least two groups")
  expect_error(riem.fanova(wrapped[[1]], wrap.euclidean(list(1, 2))), "three")
  constant <- wrap.euclidean(as.list(rep(1, 4)))
  expect_error(riem.fanova(constant, constant), "degenerate")
})

test_that("ANOVA permutations refit groups and use inclusive Monte Carlo p-values", {
  X <- wrap.euclidean(as.list(c(-1, 0, 2, 3)))
  Y <- wrap.euclidean(as.list(c(0, 1, 4, 8)))
  set.seed(17)
  first <- riem.fanovaP(X, Y, nperm = 19)
  set.seed(17)
  second <- riem.fanovaP(X, Y, nperm = 19)
  expect_equal(first$permutation_statistics, second$permutation_statistics)
  expect_equal(first$p.value, (1 + sum(first$permutation_statistics >= first$statistic)) / 20)
  expect_equal(length(first$permutation_statistics), 19)
  expect_identical(first$calibration, "random_label_permutation")
  expect_error(riem.fanovaP(X, Y, nperm = 0), "nperm")
})

test_that("hierarchical clustering delegates to the supported stats implementation", {
  x <- c(0, 1, 4, 8)
  X <- wrap.euclidean(matrix(x, ncol = 1))
  expected <- hclust(dist(x), method = "complete")
  actual <- riem.hclust(X, method = "complete")
  expect_equal(actual$merge, expected$merge)
  expect_equal(actual$height, expected$height)
  expect_s3_class(actual, "hclust")
  expect_identical(actual$geometry$geometry_id, "euclidean")
  expect_error(riem.hclust(X, members = c(1, 0, 1, 1)), "members")
})

test_that("distance-summary permutation testing validates its actual contract", {
  X <- wrap.euclidean(as.list(c(0, 1, 2)))
  Y <- wrap.euclidean(as.list(c(3, 5, 7, 10)))
  dx <- mean(dist(c(0, 1, 2)))
  dy <- mean(dist(c(3, 5, 7, 10)))
  dxy <- mean(abs(outer(c(0, 1, 2), c(3, 5, 7, 10), "-")))
  set.seed(103)
  out <- riem.test2bg14(X, Y, nperm = 9)
  expect_equal(unname(out$statistic), (dx - dxy)^2 + (dy - dxy)^2)
  expect_equal(out$p.value, (1 + sum(out$permutation_statistics >= out$statistic)) / 10)
  expect_gte(out$p.value, 0.1)
  expect_error(riem.test2bg14(X, wrap.euclidean(list(1))), "two observations")
  expect_error(riem.test2bg14(X, Y, nperm = 0), "nperm")
  identical_data <- wrap.euclidean(as.list(rep(1, 3)))
  expect_equal(riem.test2bg14(identical_data, identical_data, nperm = 3)$p.value, 1)
})

test_that("transport validates probability mass and singleton costs", {
  X <- wrap.euclidean(as.list(c(0, 2)))
  Y <- wrap.euclidean(as.list(c(1, 5)))
  out <- riem.wasserstein(X, Y, p = 2)
  expect_equal(out$distance, sqrt(5), tolerance = 1e-10)
  expect_equal(rowSums(out$plan), c(0.5, 0.5))
  expect_equal(colSums(out$plan), c(0.5, 0.5))
  expect_identical(out$geometry$geometry_id, "euclidean")
  singleton <- riem.wasserstein(wrap.euclidean(list(0)), Y, p = 2,
                                weight2 = c(1e308, 1e308))
  expect_equal(singleton$distance, sqrt(13), tolerance = 1e-10)
  expect_equal(dim(singleton$plan), c(1L, 2L))
  expect_error(riem.wasserstein(X, Y, p = 0.5), "at least one")
  expect_error(riem.wasserstein(X, Y, weight1 = c(0, 0)), "positive")
  expect_error(riem.wasserstein(X, Y, weight1 = c(NA, 1)), "finite")
  expect_error(riem.wasserstein(X, wrap.sphere(list(c(1, 0)))), "manifold")
  set.seed(9)
  perm <- riem.test2wass(wrap.euclidean(list(0)), Y, nperm = 9)
  expect_equal(perm$statistic, c(Wmn = sqrt(13)), tolerance = 1e-10)
  expect_equal(perm$p.value, (1 + sum(perm$permutation_statistics >= perm$statistic)) / 10)
  expect_identical(perm$solver, "linear_program")
  expect_error(riem.test2wass(X, Y, nperm = 0), "nperm")
})

test_that("angular densities declare uniform probability measure and stable scaling", {
  theta <- seq(0, 2 * pi, length.out = 20001)[-20001]
  X <- cbind(cos(theta), sin(theta))
  A <- diag(c(4, 1))
  density <- dacg(X, A)
  expect_equal(mean(density), 1, tolerance = 1e-9)
  expect_equal(dacg(X[1:5, ], diag(2)), rep(1, 5), tolerance = 1e-12)
  expected <- det(A)^(-0.5) * rowSums((X[1:5, ] %*% solve(A)) * X[1:5, ])^(-1)
  expect_equal(density[1:5], expected, tolerance = 1e-12)
  expect_equal(dacg(X[1:5, ], A * 1e-250), density[1:5], tolerance = 1e-12)
  expect_equal(dacg(-X[1:5, ], A), density[1:5], tolerance = 1e-12)
  expect_equal(dacg(X[1:5, ], A, log = TRUE), log(density[1:5]), tolerance = 1e-12)
  bases <- lapply(1:5, function(i) matrix(X[i, ], ncol = 1))
  expect_equal(dmacg(bases, A), density[1:5], tolerance = 1e-12)
  expect_equal(dmacg(bases, A * 1e250, log = TRUE), log(density[1:5]), tolerance = 1e-12)
  expect_error(dmacg(bases, diag(3)), "row dimension")
  Q <- qr.Q(qr(matrix(c(1, 0, 2, 0, 1, 1), 3, 2)))
  expect_equal(dmacg(list(Q), diag(3)), 1, tolerance = 1e-12)
  S <- diag(c(2, 3, 1))
  expect_equal(dmacg(list(Q), S), dmacg(list(Q %*% matrix(c(0, 1, 1, 0), 2)), S),
               tolerance = 1e-12)
})

test_that("angular sampling and fitting retain their statistical contracts", {
  set.seed(90)
  vectors <- racg(6, diag(c(2, 1, 3)))
  expect_equal(vapply(vectors, function(x) sum(x^2), 0), rep(1, 6), tolerance = 1e-12)
  set.seed(90)
  expect_equal(racg(6, diag(c(2, 1, 3))), vectors)
  expect_error(racg(0, diag(3)), "n")
  expect_error(racg(2.5, diag(3)), "n")
  bases <- rmacg(1, 2, diag(3))
  expect_equal(dim(bases[[1]]), c(3L, 2L))
  expect_equal(crossprod(bases[[1]]), diag(2), tolerance = 1e-12)
  expect_error(rmacg(2.5, 1, diag(3)), "n")
  expect_error(rmacg(1, 4, diag(3)), "r")
  angles <- c(0, 0.21, 0.77, 1.23, 1.71, 2.23, 2.66, 3.09)
  x <- cbind(cos(angles), sin(angles))
  fit <- mle.acg(x, maxiter = 200, eps = 1e-10)
  expect_true(attr(fit, "converged"))
  expect_equal(sum(diag(fit)), 2, tolerance = 1e-12)
  q <- rowSums((x %*% solve(fit)) * x)
  fixed <- crossprod(x / sqrt(q))
  fixed <- fixed * 2 / sum(diag(fixed))
  expect_equal(unname(as.vector(fit)), as.vector(fixed), tolerance = 1e-9)
  expect_equal(attr(fit, "objective"), -mean(dacg(x, fit, log = TRUE)), tolerance = 1e-12)
  expect_warning(limited <- mle.acg(x, maxiter = 1), "did not converge")
  expect_false(attr(limited, "converged"))
  expect_error(mle.acg(matrix(rep(c(1, 0), 3), ncol = 2, byrow = TRUE)), "span")
  expect_error(mle.macg(list(diag(2), diag(2))), "not identifiable")
  expect_error(mle.acg(x, eps = 0), "positive")
})

test_that("uniformity formulas reject singular dimension regimes", {
  proper <- wrap.grassmann(list(matrix(c(1, 0), ncol = 1), matrix(c(0, 1), ncol = 1)))
  expect_error(grassmann.utest(proper, method = "BingM"), "p > 2")
  out <- grassmann.utest(proper, method = "Bing")
  expect_equal(unname(out$statistic), 0, tolerance = 1e-12)
  expect_equal(out$p.value, 1)
  expect_identical(out$calibration, "asymptotic_chisquared")
  full <- wrap.grassmann(list(diag(2), diag(2)))
  expect_error(grassmann.utest(full), "proper subspace")
})
