# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

basic_pdist <- function(mfdname, data, dtype) {
    .Call('_Riemann_basic_pdist', PACKAGE = 'Riemann', mfdname, data, dtype)
}

basic_pdist2 <- function(mfdname, data1, data2, dtype) {
    .Call('_Riemann_basic_pdist2', PACKAGE = 'Riemann', mfdname, data1, data2, dtype)
}

basic_interpolate <- function(mfdname, dtype, mat1, mat2, vect) {
    .Call('_Riemann_basic_interpolate', PACKAGE = 'Riemann', mfdname, dtype, mat1, mat2, vect)
}

inference_mean_intrinsic <- function(mfdname, data, myweight, myiter, myeps) {
    .Call('_Riemann_inference_mean_intrinsic', PACKAGE = 'Riemann', mfdname, data, myweight, myiter, myeps)
}

inference_mean_extrinsic <- function(mfdname, data, myweight, myiter, myeps) {
    .Call('_Riemann_inference_mean_extrinsic', PACKAGE = 'Riemann', mfdname, data, myweight, myiter, myeps)
}

inference_median_intrinsic <- function(mfdname, data, myweight, myiter, myeps) {
    .Call('_Riemann_inference_median_intrinsic', PACKAGE = 'Riemann', mfdname, data, myweight, myiter, myeps)
}

inference_median_extrinsic <- function(mfdname, data, myweight, myiter, myeps) {
    .Call('_Riemann_inference_median_extrinsic', PACKAGE = 'Riemann', mfdname, data, myweight, myiter, myeps)
}

clustering_nmshift <- function(mfdname, data, h, iter, eps) {
    .Call('_Riemann_clustering_nmshift', PACKAGE = 'Riemann', mfdname, data, h, iter, eps)
}

clustering_kmeans_lloyd <- function(mfdname, geotype, data, iter, eps, initlabel) {
    .Call('_Riemann_clustering_kmeans_lloyd', PACKAGE = 'Riemann', mfdname, geotype, data, iter, eps, initlabel)
}

clustering_kmeans_macqueen <- function(mfdname, geotype, data, iter, eps, initlabel) {
    .Call('_Riemann_clustering_kmeans_macqueen', PACKAGE = 'Riemann', mfdname, geotype, data, iter, eps, initlabel)
}

clustering_clrq <- function(mfdname, data, init_label, par_a, par_b) {
    .Call('_Riemann_clustering_clrq', PACKAGE = 'Riemann', mfdname, data, init_label, par_a, par_b)
}

clustering_sup_intrinsic <- function(mfdname, data, weight, multiplier, maxiter, eps) {
    .Call('_Riemann_clustering_sup_intrinsic', PACKAGE = 'Riemann', mfdname, data, weight, multiplier, maxiter, eps)
}

visualize_pga <- function(mfdname, data) {
    .Call('_Riemann_visualize_pga', PACKAGE = 'Riemann', mfdname, data)
}

learning_seb <- function(mfdname, data, myiter, myeps, method) {
    .Call('_Riemann_learning_seb', PACKAGE = 'Riemann', mfdname, data, myiter, myeps, method)
}

learning_rmml <- function(mfdname, data, lambda, label) {
    .Call('_Riemann_learning_rmml', PACKAGE = 'Riemann', mfdname, data, lambda, label)
}

runif_sphere <- function(n, p) {
    .Call('_Riemann_runif_sphere', PACKAGE = 'Riemann', n, p)
}

runif_stiefel <- function(p, k, N) {
    .Call('_Riemann_runif_stiefel', PACKAGE = 'Riemann', p, k, N)
}

mat_rank <- function(A) {
    .Call('_Riemann_mat_rank', PACKAGE = 'Riemann', A)
}

mat_symm <- function(A, diag) {
    .Call('_Riemann_mat_symm', PACKAGE = 'Riemann', A, diag)
}

mat_diaghalf <- function(D) {
    .Call('_Riemann_mat_diaghalf', PACKAGE = 'Riemann', D)
}

mat_diaginvhalf <- function(D) {
    .Call('_Riemann_mat_diaginvhalf', PACKAGE = 'Riemann', D)
}

mat_cov2cor <- function(A) {
    .Call('_Riemann_mat_cov2cor', PACKAGE = 'Riemann', A)
}

