# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_ipot20 <- function(a, b, dab, lambda, p, maxiter, abstol, L) {
    .Call('_Riemann_cpp_ipot20', PACKAGE = 'Riemann', a, b, dab, lambda, p, maxiter, abstol, L)
}

cpp_pdist <- function(X) {
    .Call('_Riemann_cpp_pdist', PACKAGE = 'Riemann', X)
}

macg_mle <- function(data, maxiter, abstol) {
    .Call('_Riemann_macg_mle', PACKAGE = 'Riemann', data, maxiter, abstol)
}

macg_sample <- function(n, r, sigma) {
    .Call('_Riemann_macg_sample', PACKAGE = 'Riemann', n, r, sigma)
}

macg_density <- function(data, sigma) {
    .Call('_Riemann_macg_density', PACKAGE = 'Riemann', data, sigma)
}

acg_mle <- function(data, maxiter, abstol) {
    .Call('_Riemann_acg_mle', PACKAGE = 'Riemann', data, maxiter, abstol)
}

acg_density <- function(data, A) {
    .Call('_Riemann_acg_density', PACKAGE = 'Riemann', data, A)
}

cppdist_int_1toN <- function(x, Y) {
    .Call('_Riemann_cppdist_int_1toN', PACKAGE = 'Riemann', x, Y)
}

cppdist_ext_1toN <- function(x, Y) {
    .Call('_Riemann_cppdist_ext_1toN', PACKAGE = 'Riemann', x, Y)
}

basic_pdist <- function(mfdname, data, dtype) {
    .Call('_Riemann_basic_pdist', PACKAGE = 'Riemann', mfdname, data, dtype)
}

basic_pdist2 <- function(mfdname, data1, data2, dtype) {
    .Call('_Riemann_basic_pdist2', PACKAGE = 'Riemann', mfdname, data1, data2, dtype)
}

basic_interpolate <- function(mfdname, dtype, mat1, mat2, vect) {
    .Call('_Riemann_basic_interpolate', PACKAGE = 'Riemann', mfdname, dtype, mat1, mat2, vect)
}

inference_mean_intrinsic <- function(mfdname, data, myweight, myiter, myeps) {
    .Call('_Riemann_inference_mean_intrinsic', PACKAGE = 'Riemann', mfdname, data, myweight, myiter, myeps)
}

inference_mean_extrinsic <- function(mfdname, data, myweight, myiter, myeps) {
    .Call('_Riemann_inference_mean_extrinsic', PACKAGE = 'Riemann', mfdname, data, myweight, myiter, myeps)
}

inference_median_intrinsic <- function(mfdname, data, myweight, myiter, myeps) {
    .Call('_Riemann_inference_median_intrinsic', PACKAGE = 'Riemann', mfdname, data, myweight, myiter, myeps)
}

inference_median_extrinsic <- function(mfdname, data, myweight, myiter, myeps) {
    .Call('_Riemann_inference_median_extrinsic', PACKAGE = 'Riemann', mfdname, data, myweight, myiter, myeps)
}

clustering_nmshift <- function(mfdname, data, h, iter, eps) {
    .Call('_Riemann_clustering_nmshift', PACKAGE = 'Riemann', mfdname, data, h, iter, eps)
}

clustering_kmeans_lloyd <- function(mfdname, geotype, data, iter, eps, initlabel) {
    .Call('_Riemann_clustering_kmeans_lloyd', PACKAGE = 'Riemann', mfdname, geotype, data, iter, eps, initlabel)
}

clustering_kmeans_macqueen <- function(mfdname, geotype, data, iter, eps, initlabel) {
    .Call('_Riemann_clustering_kmeans_macqueen', PACKAGE = 'Riemann', mfdname, geotype, data, iter, eps, initlabel)
}

clustering_clrq <- function(mfdname, data, init_label, par_a, par_b) {
    .Call('_Riemann_clustering_clrq', PACKAGE = 'Riemann', mfdname, data, init_label, par_a, par_b)
}

clustering_sup_intrinsic <- function(mfdname, data, weight, multiplier, maxiter, eps) {
    .Call('_Riemann_clustering_sup_intrinsic', PACKAGE = 'Riemann', mfdname, data, weight, multiplier, maxiter, eps)
}

clustering_kmeans18B <- function(mfdname, geotype, data, K, M, maxiter) {
    .Call('_Riemann_clustering_kmeans18B', PACKAGE = 'Riemann', mfdname, geotype, data, K, M, maxiter)
}

cvi_internal_score <- function(mfd, dtype, data, mylabel) {
    .Call('_Riemann_cvi_internal_score', PACKAGE = 'Riemann', mfd, dtype, data, mylabel)
}

cvi_internal_gdxx <- function(mfd, dtype, data, mylabel, delta, Delta) {
    .Call('_Riemann_cvi_internal_gdxx', PACKAGE = 'Riemann', mfd, dtype, data, mylabel, delta, Delta)
}

cvi_internal_db <- function(mfd, dtype, data, mylabel) {
    .Call('_Riemann_cvi_internal_db', PACKAGE = 'Riemann', mfd, dtype, data, mylabel)
}

cvi_internal_ci <- function(mfd, dtype, data, mylabel) {
    .Call('_Riemann_cvi_internal_ci', PACKAGE = 'Riemann', mfd, dtype, data, mylabel)
}

cvi_internal_ch <- function(mfd, dtype, data, mylabel) {
    .Call('_Riemann_cvi_internal_ch', PACKAGE = 'Riemann', mfd, dtype, data, mylabel)
}

cvi_internal_dunn <- function(mfd, dtype, data, mylabel) {
    .Call('_Riemann_cvi_internal_dunn', PACKAGE = 'Riemann', mfd, dtype, data, mylabel)
}

visualize_pga <- function(mfdname, data) {
    .Call('_Riemann_visualize_pga', PACKAGE = 'Riemann', mfdname, data)
}

visualize_kpca <- function(mfdname, data, sigma, ndim) {
    .Call('_Riemann_visualize_kpca', PACKAGE = 'Riemann', mfdname, data, sigma, ndim)
}

visualize_isomap <- function(mfdname, data, geometry, nnbd) {
    .Call('_Riemann_visualize_isomap', PACKAGE = 'Riemann', mfdname, data, geometry, nnbd)
}

visualize_cmds <- function(mfd, geo, data, ndim) {
    .Call('_Riemann_visualize_cmds', PACKAGE = 'Riemann', mfd, geo, data, ndim)
}

visualize_sammon <- function(mfd, geo, data, ndim, maxiter, abstol) {
    .Call('_Riemann_visualize_sammon', PACKAGE = 'Riemann', mfd, geo, data, ndim, maxiter, abstol)
}

curvedist_lp <- function(mfd, geo, data1, data2, vect, myp) {
    .Call('_Riemann_curvedist_lp', PACKAGE = 'Riemann', mfd, geo, data1, data2, vect, myp)
}

curvedist_dtwbasic <- function(mfd, geo, data1, data2) {
    .Call('_Riemann_curvedist_dtwbasic', PACKAGE = 'Riemann', mfd, geo, data1, data2)
}

learning_seb <- function(mfdname, data, myiter, myeps, method) {
    .Call('_Riemann_learning_seb', PACKAGE = 'Riemann', mfdname, data, myiter, myeps, method)
}

learning_rmml <- function(mfdname, data, lambda, label) {
    .Call('_Riemann_learning_rmml', PACKAGE = 'Riemann', mfdname, data, lambda, label)
}

learning_coreset18B <- function(mfdname, geoname, data, M, myiter, myeps) {
    .Call('_Riemann_learning_coreset18B', PACKAGE = 'Riemann', mfdname, geoname, data, M, myiter, myeps)
}

runif_sphere <- function(n, p) {
    .Call('_Riemann_runif_sphere', PACKAGE = 'Riemann', n, p)
}

runif_stiefel <- function(p, k, N) {
    .Call('_Riemann_runif_stiefel', PACKAGE = 'Riemann', p, k, N)
}

spdwass_sylvester <- function(A, X) {
    .Call('_Riemann_spdwass_sylvester', PACKAGE = 'Riemann', A, X)
}

spdwass_log <- function(C, X) {
    .Call('_Riemann_spdwass_log', PACKAGE = 'Riemann', C, X)
}

spdwass_exp <- function(C, V, t = 1.0) {
    .Call('_Riemann_spdwass_exp', PACKAGE = 'Riemann', C, V, t)
}

spdwass_metric <- function(S, X, Y) {
    .Call('_Riemann_spdwass_metric', PACKAGE = 'Riemann', S, X, Y)
}

spdwass_baryRU02 <- function(spdlist, weight, maxiter, abstol) {
    .Call('_Riemann_spdwass_baryRU02', PACKAGE = 'Riemann', spdlist, weight, maxiter, abstol)
}

spdwass_baryAE16 <- function(spdlist, weight, maxiter, abstol) {
    .Call('_Riemann_spdwass_baryAE16', PACKAGE = 'Riemann', spdlist, weight, maxiter, abstol)
}

src_spd_pdist <- function(data, geometry) {
    .Call('_Riemann_src_spd_pdist', PACKAGE = 'Riemann', data, geometry)
}

mat_rank <- function(A) {
    .Call('_Riemann_mat_rank', PACKAGE = 'Riemann', A)
}

mat_symm <- function(A, diag) {
    .Call('_Riemann_mat_symm', PACKAGE = 'Riemann', A, diag)
}

mat_diaghalf <- function(D) {
    .Call('_Riemann_mat_diaghalf', PACKAGE = 'Riemann', D)
}

mat_diaginvhalf <- function(D) {
    .Call('_Riemann_mat_diaginvhalf', PACKAGE = 'Riemann', D)
}

mat_cov2cor <- function(A) {
    .Call('_Riemann_mat_cov2cor', PACKAGE = 'Riemann', A)
}

cpp_rmvnorm <- function(n, mu, sigma) {
    .Call('_Riemann_cpp_rmvnorm', PACKAGE = 'Riemann', n, mu, sigma)
}

